[workspace]
members = ["src-tauri", "warp-rail", "weaverail-io", "weaverail-model", "weaverail-object", "weft-rail"]
resolver = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[workspace.package]
version = "0.2.2"
edition = "2024"
authors = ["akashiyaki01c"]
description = "Weaverail"
documentation = "https://github.com/akashiyaki01c/weaverail"
