[package]
name = "weft-rail"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
petgraph = "0.8.3"
weaverail-model = { path = "../weaverail-model" }
uuid = { version = "1.22.0", features = ["serde", "v4"] }
