[package]
name = "weaverail-testdata"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ron = "0.12.2"
weaverail-model = { path = "../weaverail-model" }
weaverail-operation = { path = "../weaverail-operation" }
zstd = "0.13.3"
