// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentRef } from "./SegmentRef";

/**
 * ダイヤグラムの縦軸の区間を表す
 */
export type DiagramViewSegment = { "Black": { scale: number, } } | { "StationBetween": { segment: SegmentRef, } };
