// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { IdIssuer } from "./IdIssuer";
import type { Line } from "./Line";
import type { LineId } from "./LineId";
import type { LineSegment } from "./LineSegment";
import type { LineSegmentId } from "./LineSegmentId";
import type { Station } from "./Station";
import type { StationId } from "./StationId";
import type { TemplateTrain } from "./TemplateTrain";
import type { TemplateTrainId } from "./TemplateTrainId";
import type { Timetable } from "./Timetable";
import type { TimetableId } from "./TimetableId";
import type { Track } from "./Track";
import type { TrackId } from "./TrackId";
import type { Train } from "./Train";
import type { TrainId } from "./TrainId";
import type { TrainType } from "./TrainType";
import type { TrainTypeId } from "./TrainTypeId";

/**
 * ダイヤグラムプロジェクトファイルを表す構造体
 */
export type DiagramRoot = { 
/**
 * 駅の集合
 */
stations: { [key in StationId]: Station }, 
/**
 * 番線の集合
 */
tracks: { [key in TrackId]: Track }, 
/**
 * 駅間の集合
 */
segments: { [key in LineSegmentId]: LineSegment }, 
/**
 * 路線の集合
 */
lines: { [key in LineId]: Line }, 
/**
 * 列車種別の集合
 */
train_types: { [key in TrainTypeId]: TrainType }, 
/**
 * テンプレート列車の集合
 */
template_trains: { [key in TemplateTrainId]: TemplateTrain }, 
/**
 * 時刻表の集合
 */
timetables: { [key in TimetableId]: Timetable }, 
/**
 * 列車の集合
 */
trains: { [key in TrainId]: Train }, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, 
/**
 * ID発行
 */
id_issuer: IdIssuer, };
