// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagramLogicalConvert = { scale_x: number, scale_y: number, offset_x: number, offset_y: number, };
