// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagramViewSegment } from "./DiagramViewSegment";
import type { DiagramViewSettingsId } from "./DiagramViewSettingsId";
import type { ExtensionProperty } from "./ExtensionProperty";

/**
 * ダイヤグラムを表示する際の設定を表す
 */
export type DiagramViewSettings = { 
/**
 * 設定の識別子
 */
id: DiagramViewSettingsId, 
/**
 * 設定の名前
 */
name: string, 
/**
 * ダイヤグラムの縦軸の区間の一覧を表す
 */
segments: Array<DiagramViewSegment>, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
