// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { Line } from "./Line";
import type { Station } from "./Station";
import type { TemplateTrain } from "./TemplateTrain";
import type { Timetable } from "./Timetable";
import type { TrainType } from "./TrainType";

/**
 * ダイヤグラムファイル
 */
export type DiagramRoot = { 
/**
 * 駅の集合
 */
stations: { [key in string]: Station }, 
/**
 * 路線の集合
 */
lines: { [key in string]: Line }, 
/**
 * 列車種別の集合
 */
train_types: { [key in string]: TrainType }, 
/**
 * テンプレート列車の集合
 */
template_trains: { [key in string]: TemplateTrain }, 
/**
 * 時刻表の集合
 */
timetables: { [key in string]: Timetable }, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
