// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * ユーザ定義で拡張が行える拡張プロパティを表す構造体
 */
export type ExtensionProperty = { [key in string]: JsonValue };
