// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Heddle } from "./Heddle";

/**
 * ユーザ定義で拡張が行える拡張プロパティを表す構造体
 */
export type ExtensionProperty = { [key in string]: Heddle };
