// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Time } from "./Time";
import type { WeaverailId } from "./WeaverailId";

/**
 * オブジェクトを走査する際のオブジェクトを表す
 */
export type Heddle = "Null" | { "Id": WeaverailId } | { "Boolean": boolean } | { "U8": number } | { "I8": number } | { "U16": number } | { "I16": number } | { "U32": number } | { "I32": number } | { "U64": bigint } | { "I64": bigint } | { "U128": bigint } | { "I128": bigint } | { "F32": number } | { "F64": number } | { "String": string } | { "Array": Array<Heddle> } | { "Compound": { [key in Heddle]?: Heddle } } | { "Time": Time };
