// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { LineSegmentId } from "./LineSegmentId";
import type { StationId } from "./StationId";

/**
 * Weaverail上の1つの路線に属する駅間を表す構造体
 */
export type LineSegment = { 
/**
 * 識別ID
 */
id: LineSegmentId, 
/**
 * 開始駅ID
 */
start_station: StationId, 
/**
 * 終了駅ID
 */
end_station: StationId, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
