// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { LineId } from "./LineId";
import type { SegmentRef } from "./SegmentRef";

/**
 * Weaverail上の1つの路線を表す構造体
 */
export type Line = { 
/**
 * 識別ID
 */
id: LineId, 
/**
 * 路線名 (例: "神明線")
 */
name: string, 
/**
 * 路線に所属する駅間リスト
 */
segments: Array<SegmentRef>, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
