// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";

/**
 * 一つの駅間を表す
 */
export type LineSegment = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 開始駅ID
 */
start_station: string, 
/**
 * 終了駅ID
 */
end_station: string, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
