// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { LineSegment } from "./LineSegment";

/**
 * 一つの路線を表す
 */
export type Line = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 路線名
 */
name: string, 
/**
 * 所属する駅ID
 */
segments: Array<LineSegment>, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
