// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultWeftTime } from "./ResultWeftTime";
import type { TrainId } from "./TrainId";

export type ResultWeftTrain = { train_id: TrainId, times: Array<ResultWeftTime>, };
