// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultSvgTrain } from "./ResultSvgTrain";

export type ResultSvg = { trains: Array<ResultSvgTrain>, };
