// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainId } from "./TrainId";

export type ResultSvgTrain = { train_id: TrainId, path_string: string, };
