// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineSegmentId } from "./LineSegmentId";
import type { StationId } from "./StationId";
import type { StopType } from "./StopType";
import type { Time } from "./Time";
import type { TrainId } from "./TrainId";

export type ResultWeftTime = { train_id: TrainId, before_segment_id: LineSegmentId | null, next_segment_id: LineSegmentId | null, station_id: StationId, arrival_time: Time | null, departure_time: Time | null, stop_type: StopType, };
