// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { LineSegmentId } from "./LineSegmentId";
import type { TrainId } from "./TrainId";

/**
 * 駅間での列車の順序を表す
 */
export type SegmentTrainOrder = { segment_id: LineSegmentId, is_reversed: boolean, order: Array<TrainId>, properties: ExtensionProperty, };
