// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineSegmentId } from "./LineSegmentId";

/**
 * 駅間への参照を表す構造体
 */
export type SegmentRef = { segment_id: LineSegmentId, is_reversed: boolean, };
