// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentTrainOrder } from "./SegmentTrainOrder";

export type SegmentTrainOrders = { 
/**
 * 順行列車
 */
prograde: SegmentTrainOrder, 
/**
 * 逆行列車
 */
retrograde: SegmentTrainOrder, };
