// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainId } from "./TrainId";

/**
 * 駅間での列車の順序を表す
 */
export type SegmentTrainOrder = { order: Array<TrainId>, };
