// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";

/**
 * 一つの駅を表す
 */
export type Station = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 駅名
 */
name: string, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
