// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { StationId } from "./StationId";

/**
 * Weaverail上の1つの駅を表す構造体
 */
export type Station = { 
/**
 * 識別ID
 */
id: StationId, 
/**
 * 正式駅名 (例: "梅田")
 */
name: string, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
