// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Time } from "./Time";

/**
 * 停車種別
 */
export type StopType = { "Stop": Time } | "Pass";
