// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Time } from "./Time";

/**
 * テンプレート列車の停車種別を表す列挙体
 */
export type StopType = { "Stop": Time } | "Pass";
