// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { LineSegmentId } from "./LineSegmentId";
import type { TemplateTrainSegmentId } from "./TemplateTrainSegmentId";
import type { Time } from "./Time";

/**
 * Weaverail上のテンプレート列車の駅間情報を表す構造体
 */
export type TemplateTrainSegment = { 
/**
 * 識別ID
 */
id: TemplateTrainSegmentId, 
/**
 * 駅間ID
 */
segment_id: LineSegmentId, 
/**
 * 駅間が反転しているか
 */
is_reversed: boolean, 
/**
 * 基準運転時分
 */
running_time: Time, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
