// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { TemplateTrainSegment } from "./TemplateTrainSegment";
import type { TemplateTrainStation } from "./TemplateTrainStation";

/**
 * 一つのテンプレート列車を表す
 */
export type TemplateTrain = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 列車種別ID
 */
train_type_id: string, start_station: TemplateTrainStation, 
/**
 * 駅間情報群
 */
segments: Array<[TemplateTrainSegment, TemplateTrainStation]>, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
