// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopType } from "./StopType";

/**
 * 一つのテンプレート列車の駅情報を表す
 */
export type TemplateTrainStation = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 駅ID
 */
station_id: string, 
/**
 * 停車時間
 */
stop_time: StopType, };
