// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationId } from "./StationId";
import type { StopType } from "./StopType";
import type { TemplateTrainStationId } from "./TemplateTrainStationId";
import type { TrackId } from "./TrackId";

/**
 * Weaverail上のテンプレート列車の駅情報を表す構造体
 */
export type TemplateTrainStation = { 
/**
 * 識別ID
 */
id: TemplateTrainStationId, 
/**
 * 駅ID
 */
station_id: StationId, 
/**
 * 駅到着番線ID
 */
track_id: TrackId, 
/**
 * 停車時間
 */
stop_time: StopType, };
