// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Time } from "./Time";

/**
 * 一つのテンプレート列車の駅間情報を表す
 */
export type TemplateTrainSegment = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 駅間ID
 */
segment_id: string, 
/**
 * 基準運転時分
 */
running_time: Time, };
