// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { TemplateTrainId } from "./TemplateTrainId";
import type { TemplateTrainSection } from "./TemplateTrainSection";
import type { TemplateTrainStation } from "./TemplateTrainStation";
import type { TrainTypeId } from "./TrainTypeId";

/**
 * Weaverail上の1つのテンプレート列車を表す構造体
 */
export type TemplateTrain = { 
/**
 * 識別ID
 */
id: TemplateTrainId, 
/**
 * テンプレート列車名 (例: "本線下り普通列車")
 */
name: string, 
/**
 * 列車種別ID
 */
train_type_id: TrainTypeId, 
/**
 * 開始駅情報
 */
start_station: TemplateTrainStation, 
/**
 * 駅間/駅情報の一覧
 */
segments: Array<TemplateTrainSection>, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
