// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateTrainSegment } from "./TemplateTrainSegment";
import type { TemplateTrainStation } from "./TemplateTrainStation";

export type TemplateTrainSection = { segment: TemplateTrainSegment, station: TemplateTrainStation, };
