// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationId } from "./StationId";
import type { TemplateTrainId } from "./TemplateTrainId";

/**
 * Weaverail上のテンプレート列車への部分参照
 */
export type TemplateSegment = { 
/**
 * テンプレート列車ID
 */
template_train_id: TemplateTrainId, 
/**
 * 開始駅ID
 */
start_station_id: StationId, 
/**
 * 終了駅ID
 */
end_station_id: StationId, };
