// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { LineSegmentId } from "./LineSegmentId";
import type { SegmentTrainOrder } from "./SegmentTrainOrder";
import type { TimetableId } from "./TimetableId";

/**
 * Weaverail上の1つの時刻表を表す構造体
 */
export type Timetable = { 
/**
 * 識別ID
 */
id: TimetableId, 
/**
 * 時刻表名
 */
name: string, 
/**
 * 駅間の列車順序
 */
segment_train_orders: { [key in LineSegmentId]: SegmentTrainOrder }, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
