// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { Train } from "./Train";

/**
 * 一つの時刻表を表す
 */
export type Timetable = { 
/**
 * 識別ID
 */
id: string, 
/**
 * 時刻表名
 */
name: string, 
/**
 * 時刻表に含まれる列車
 */
trains: { [key in string]: Train }, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
