// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { StationId } from "./StationId";
import type { TrackId } from "./TrackId";

/**
 * Weaverail上の駅に存在している1つの列車番線を表す構造体
 */
export type Track = { 
/**
 * 識別ID
 */
id: TrackId, 
/**
 * 駅ID
 */
station_id: StationId, 
/**
 * 番線名 (例: "1番線")
 */
name: string, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
