// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { TemplateSegment } from "./TemplateSegment";
import type { Time } from "./Time";
import type { TimetableId } from "./TimetableId";
import type { TrainId } from "./TrainId";

/**
 * Weaverail上の1つの「列車」を表す
 */
export type Train = { 
/**
 * 識別ID
 */
id: TrainId, 
/**
 * 時刻表ID
 */
timetable_id: TimetableId, 
/**
 * テンプレート列車ID
 */
template_segments: Array<TemplateSegment>, 
/**
 * 開始駅の出発時刻
 */
start_departure_time: Time, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
