// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrainsAdjustmentId } from "./TrainsAdjustmentId";
import type { TrainsAdjustmentType } from "./TrainsAdjustmentType";

/**
 * 列車同士の時刻調整を表す
 */
export type TrainsAdjustment = { 
/**
 * 識別ID
 */
id: TrainsAdjustmentId, 
/**
 * 時刻調整種別
 */
adjustment: TrainsAdjustmentType, };
