// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationId } from "./StationId";
import type { TrackId } from "./TrackId";
import type { TrainId } from "./TrainId";

/**
 * 列車同士の時刻調整種別を表す
 */
export type TrainsAdjustmentType = "None" | { "Waiting": { 
/**
 * 待避を行う駅ID
 */
station_id: StationId, 
/**
 * (変更がある場合)待避列車の番線ID
 */
waiting_track_id: TrackId | null, 
/**
 * 待避側の列車ID
 */
waiting_train_id: TrainId, 
/**
 * 通過側の列車ID
 */
passing_train_id: TrainId, } };
