// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionProperty } from "./ExtensionProperty";
import type { Time } from "./Time";

/**
 * 一つの列車を表す
 */
export type Train = { 
/**
 * 識別ID
 */
id: string, 
/**
 * テンプレート列車ID
 */
template_train_id: string, 
/**
 * 開始駅ID
 */
start_station_id: string, 
/**
 * 終了駅ID
 */
end_station_id: string, 
/**
 * 開始駅の出発時刻
 */
start_departure_time: Time, 
/**
 * 拡張プロパティ
 */
properties: ExtensionProperty, };
