[package]
name = "weaverail-io"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
weaverail-model = { path = "../weaverail-model" }
weaverail-testdata = { path = "../weaverail-testdata" }
ron = "0.12.1"
zstd = "0.13.3"
thiserror = "2.0.18"
indexmap = { version = "2.14.0", features = ["serde"] }
