name: Tauri Release Build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
      - name: Install dependencies (Windows only)
        if: runner.os == 'Windows'
        run: choco install -y wixtoolset

      - name: Install dependencies (macOS only)
        if: runner.os == 'macOS'
        run: brew install create-dmg

      - name: Install npm deps
        run: npm ci

      - name: Build with Tauri
        run: npx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: |
            src-tauri/target/release/bundle/**
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
